### ISSUE TITLE
Translation table 25 is not supported

### ISSUE THREAD

**Issue by MadsAlbertsen** [Victorian-Bioinformatics-Consortium/prokka#43]
Prokka does not support translation table 25: http://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG25

**Comment by tseemann** [comment]
@MadsAlbertsen  - seems to be some progress with your request: https://github.com/hyattpd/Prodigal/issues/4

**Comment by tseemann** [comment]
I've updated the Linux Prodigal to one that supports table 25, and allowed --gcode 25 to be used: 99c7174a1c24c0a4a1c72d41a75b5f45de4fa986 and https://github.com/hyattpd/Prodigal/commit/79deb9500d0d0ced567a39236ef421762b5fc7e0

**AND**

Bioperl now supports it: https://github.com/bioperl/bioperl-live/issues/90

**BUT**

You need to have the latest bioperl-live (and I can't even install it on Ubuntu 12 currently because my Perl is too old).
