### ISSUE TITLE
minced version upgrade error

### ISSUE THREAD

**Issue by chandni177** [Victorian-Bioinformatics-Consortium/prokka#50]
Hi,

I recently queued Prokka for a large dataset - split into 7-8 parts so I could run them all together. AFter they all finished, my next script to extract output data failed for some runs. Upon some investigation I saw that there were a few failed runs with the log entry - 
" Prokka needs minced 1.6 or higher. Please upgrade and try again. "

I am not sure why this error came up for only some runs while the others finished successfully. It was an extremely small fraction of the total runs, and I just queued those contigs again - but I thought worthwhile to mention it here, in case someone else had a similar issue.

Thanks!
Chandni

**Comment by tseemann** [comment]
@ingled  Mark Schultz contacted VLSCI about this (which should be your first point of call for VLSCI running issues). It turns out barcoo and merri had different Prokka versions and defaults, and that module java wasn't listed as a dependency. Also Java 1.8 now fixes a memory bug that affected Slurm accounting too. Open a new issue if you still have problems.
