### ISSUE TITLE
Test run: error on the cat-parallel-hmmscan step

### ISSUE THREAD

**Issue by xapple** [Victorian-Bioinformatics-Consortium/prokka#61]
I just tried to run `prokka` on a test sequence that I placed in the file `contig.fasta`. It chokes along the way with a inscrutable error:

    xapple@cluster test $ ls
    contig.fasta
    xapple@cluster test $ head -n 2 contig.fasta
    >contig-0 9101 nucleotides
    TCTCCCGCTTGTTGAGCGAGATCCAGCACCAACTCCCCCACCGGACTTTACCAGCTATTG
    xapple@cluster test $ prokka --outdir ./ --cpus 4 --locustag prokka --compliant --usegenus --metagenome --addgene --quiet --force contig.fasta
    [02:39:58] Could not run command: cat \.\/\/proteins\.faa | parallel --gnu -j 4 --block 81 --recstart '>' --pipe hmmscan --noali --notextw --acc -E 1e-06 --cpu 1 /homeappl/home/eiler/programs/prokka110/bin/../db/hmm/HAMAP.hmm /dev/stdin > \.\/\/proteins\.bls 2> /dev/null
    xapple@cluster test $ ls
    contig.fasta         prokka_01132015.log  proteins.faa
    prokka_01132015.fna  proteins.bls
    xapple@cluster test $ parallel -V
    GNU parallel 20141122
    xapple@cluster test $ prokka -V
    prokka 1.10

However, if I copy-paste the command that supposedly went wrong onto a new shell, it exits with status 4. That is not even defined as far as I know the bash shell.

    xapple@cluster test $ cat \.\/\/proteins\.faa | parallel --gnu -j 4 --block 81 --recstart '>' --pipe hmmscan --noali --notextw --acc -E 1e-06 --cpu 1 /homeappl/home/eiler/programs/prokka110/bin/../db/hmm/HAMAP.hmm /dev/stdin > \.\/\/proteins\.bls 2> /dev/null
    xapple@cluster test $ echo $?
    4

Removing the strange character escaping does not change the result:

    xapple@cluster test $ cat proteins.faa | parallel --gnu -j 4 --block 81 --recstart '>' --pipe hmmscan --noali --notextw --acc -E 1e-06 --cpu 1 /homeappl/home/eiler/programs/prokka110/bin/../db/hmm/HAMAP.hmm /dev/stdin > proteins.bls 2> /dev/null
    xapple@cluster test $ echo $?
    4

Any ideas how to fix this ?

**Comment by aleimba** [comment]
Hi @xapple,

according to GNU parallel: Exit status will be the number of jobs failed (https://www.gnu.org/software/parallel/man.html#EXIT-STATUS).
Since `hmmscan` seems to be failing you might want to try that command separately:
```bash
hmmscan --noali --notextw --acc -E 1e-06 --cpu 1 /homeappl/home/eiler/programs/prokka110/bin/../db/hmm/HAMAP.hmm proteins.faa
```
So, either `hmmscan` doesn't run on your system correctly or *HAMAP.hmm* doesn't exist in the given path.

Have you downloaded Prokka from the GitHub repository or downloaded it from here: http://www.vicbioinformatics.com/software.prokka.shtml? Because the GitHub version is missing some of the big database files (including *db/hmm*, see also #25 and #12). If this is the case use the version from the VBC website which includes **all** databases.

HTH,
Andreas

**Comment by xapple** [comment]
OK that was it, there was no file at `/prokka110/bin/../db/hmm/HAMAP.hmm proteins.faa`. You **really** need better error messages in that case...

I had indeed downloaded prokka simply from github. Again, what can I say, If the release available on github is not functional, I would advise not to put it there.

**Comment by aleimba** [comment]
While I don't necessarily agree in removing the release, a big visual text in the README.md under [Download](https://github.com/Victorian-Bioinformatics-Consortium/prokka#download) (and [FAQs](https://github.com/Victorian-Bioinformatics-Consortium/prokka#faq), I guess) considering the 'big file' database issue would certainly be good. And of course either a concise error message or a test at the beginning of the script to check for the local databases (best integrated in `--setupdb`).

Since this apparently has come up several times, do you wan't to raise another specific issue adressing this or should I?

Disclaimer: I'm not a developer in this project, but please report back with more bugs if you find any (if they haven't been adressed in previous issues that is ;-)).
