### ISSUE TITLE
Number of aa does not match number of codon in the respective gene

### ISSUE THREAD

**Issue by efr3m** [Victorian-Bioinformatics-Consortium/prokka#64]
I have a strange problem.
I annotated my genomes with prokka 1.10.

After few issues everything was fine.

I checked some protein in the .faa file and compared with the repsective gene in the .fnc file.

There are two things I do not understand:
1- why there is always a * after the aa seq?
2- why the number of aa does not match the number of codon. I make an example, I have  a gene of 420 nucletide. I would expect a protein of 140 aa (420/3). Why the protein is 139?

Mybe is a naive question, but I cannot figure out the answer.

**Comment by efr3m** [comment]
Sorry....I did not consider the stop codon...-_-
Please insult me!

**Comment by aleimba** [comment]
Hi @efr3m again,
'*' is a character for the stop codon, see also issue #54 (which also adresses non-methionine start codons).
The protein has only 139 aa, because the nucleotide position of course includes the stop codon.

You have two choices:
 1. Use my fork, however it's based on 1.9.1-testing:
https://github.com/aleimba/prokka
There have been a couple of changes since then, see: https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/doc/ChangeLog.txt

 2. The better solution is probably to create your *.faa files from the GENBANK file, e.g. with a tool from the EMBOSS package:
http://emboss.sourceforge.net/apps/release/6.6/emboss/apps/extractfeat.html 
I also have a script that does that:
https://github.com/aleimba/bac-genomics-scripts/tree/master/cds_extractor

Cheers

**Comment by efr3m** [comment]
Thanks for spending time to deal with newby like me!

**Comment by tseemann** [comment]
Fixed as part of 23461819f4af19166fa3cf9940283f11acf42b1d

PS. @aleimba thanks for helping @efr3m  and other people on these github issues, i've been overwhelmed the last few months during moving to a new job.
