### ISSUE TITLE
Weird bioperl / barrnap error

### ISSUE THREAD

**Issue by john-nash** [Victorian-Bioinformatics-Consortium/prokka#79]
I installed prokka 1.11 and ran into the aforementioned contig length issue. Fine... I can wait until it's running again, so I back-tracked our system to using version 1.9. 

To upgrade prokka from 1.9 to 1.11, I had to upgrade barrnap (0.3 to 0.6) and bioperl (to 1.6.924). Now I cannot get prokka 1.9 to work. I get:

etc...
etc...
Running Barrnap with 8 threads

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'barrnap --threads 8 --quiet PROKKA_03022015/PROKKA_03022015.fna  |': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl5/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /usr/local/share/perl5/Bio/Root/IO.pm:270
STACK: Bio::Tools::GFF::new /usr/local/share/perl5/Bio/Tools/GFF.pm:200
STACK: /usr/molbin/prokka/bin/prokka:474

Even when I backtrack barrnap to 0.3 - has something in the bioperl update broken the barrnap script?

My command line is:
$ prokka --compliant --force file.fasta

The file.fast is a single contig of a finished genome and its header is:
\> S_Nitra ST403

and its my standard "test of new prokka install" genome.

PROKKA_03022015/PROKKA_03022015.fna is there - I looked.

Any hints?

John

**Comment by tseemann** [comment]
That error is to do with Prokka opening Barrnap and reading it's output from a pipe.


Prokka 1.11 and 1.12 open it using the new clearer syntax:

    open my $BARRNAP, '-|', "barrnap ..."

It looks like your error comes from an old version of Prokka, because the error looks like the old syntax with the pipe at the end?

    barrnap --threads 8 --quiet PROKKA_03022015/PROKKA_03022015.fna |

I'm not really sure what has happened. Does your prokka.log file say it is 1.11 and barrnap is 0.6 ?

Barrnap 0.6 is quite new, so maybe there some wierdness. DOes using 0.5 solve it?

https://github.com/Victorian-Bioinformatics-Consortium/barrnap/releases/tag/0.5

**Comment by john-nash** [comment]
It turns out not to be prokka or barrnap. It's bioperl.  It works fine with bioperl-1.6.923 and breaks with bioperl-1.6.924.

Prokka 1.12?  Please tell me more :) I only see 1.11

**Comment by tseemann** [comment]
John
I just did a fresh CPAN install of BioPerl last week (or so I thought) but it still seems to be 1.6.923
I will try 1.6.924 and see what happens.
And 1.12 is not released yet (I meant 1.10 and 1.11).
Will you be at ABPHM in May this year?
Torst

**Comment by tseemann** [comment]
@john-nash  I got 1.6.924 install properly, and ran a few Prokka tests, it seems to work, include Barrnap from Prokka and separately.  

Are you sure it was using Prokka 1.11  and not an old version?

(As an aside, I realise the Prokka version does not go in the .LOG file, so i'll file an Issue for that!)

**Comment by john-nash** [comment]
Thanks for that Torst.  My installation of bioperl 1.6.924 was a bit problematic, and maybe I need to look at that. My Dell R910 is still running an older Centos, and maybe perl 5.10 (the default) and 1.6.924 do not get along.

It really was 1.11 (I usually run a version check before symlinking prokka to a pathed folder). 

Yes, I intend to go to ABPHM in May - will you be there?

John

**Comment by tseemann** [comment]
@john-nash Yes, I'll be at ABPHM. There will be 5 of us from my new workplace this time!  Looking forward to it. 

I had some problem installed BioPerl 1.6.924 in that an old Bio/Root.pm was being used for the install, which confused things because they've separated Bio::Root now. How I solved it was to essentially remove the _whole_ Bio:: hierarchy (for me this meant ``mv /usr/share/perl/Bio /usr/share/perl/Bio.old`` and _then_ do a fresh install from CPAN.

**Comment by john-nash** [comment]
sorry I am late replying.  too much paper pushing, not enough science.

I figured out that bioperl issue as well - the upgrade crashed and I also discovered that by deleting the Bio hierarchy and reinstalling bioperl, things started working again.  Thanks for that.

@tseemann I'm madly trying to get my ABPHM2015 abstract ready for tomorrow's deadline.

**Comment by tseemann** [comment]
@john-nash Yeah, the nuke and reinstall Bio/* worked a treat for me too. I just got my abstract submitted, now onto more paper pushing with the fellowship application due next week!
