### ISSUE TITLE
not a readable FASTA file error

### ISSUE THREAD

**Issue by Biomicrogen** [Victorian-Bioinformatics-Consortium/prokka#86]
Heya Torsten,

I'm inputing a FASTA file containing all my contigs and I keep getting this error? 
'Abyss-85-2kbp.fasta' is not a readable non-empty FASTA file.
Any ideas?  It's a simple file with just a small file name (>contig 30) and then the consensus sequence after it.  There are about 250 individual contigs.

Thanks
Brandon

**Comment by Biomicrogen** [comment]
NM I figured it out, the file name was to complex, after renaming it and taking out the hyphens it worked.

**Comment by tseemann** [comment]
@Biomicrogen That filename should not cause any problems, especially hyphens. I created a file with that name and it worked. For that message to be produced, the file must fail one of these tests: (1)  have read permissions (2) be a real file not a folder (3) have a size greater than 0 bytes.

But glad you solved it.

**Comment by carlosandrecds** [comment]
Hello, I had this problem here too... it can be simple to solve, just use "prokka contigs.fasta" instead "prokka contigs.fa" cause this will depend from you linux distro.

**Comment by BMarianaRP** [comment]
Hi! I have the same problem, but I'm working with metagenomes. Is there a limit to the fasta file size? My file is pretty huge, which is the only difference between other analyses I've done with the same pipeline. Thanks for your help!

**Comment by tseemann** [comment]
@carlosandrecds `contigs.fa` / `contigs.fasta` is the name of the file containing sequences you wish to annotate. Prokka does not care what you have called that file, it will work even if it is called `super21.docx` as long it is a valid FASTA file.

**Comment by RotimiDada** [comment]
@tseemann I am also grappling with the problem @Biomicrogen experienced. I have all the contigs in a folder and did not set read permission for the folder. I however don't understand what you mean by the file having 'a size greater than 0 bytes' as a possible cause of the error! 

_Here is the script I wrote for the multiple files:
for file in .. prokka-analysis/*_scaffolds.fasta; do
prefix='basename $file'
prokka --outdir $prefix --prefix $prefix $file 
done_

And I get this: 
**This is prokka 1.13
[18:30:14] Written by Torsten Seemann <torsten.seemann@gmail.com>
[18:30:14] Homepage is https://github.com/tseemann/prokka
[18:30:14] Local time is Sun Apr 28 18:30:14 2019
[18:30:14] You are rd13
[18:30:14] Operating system is darwin
[18:30:14] You have BioPerl 1.006924
[18:30:15] System has 2 cores.
[18:30:15] Option --cpu asked for 8 cores, but system only has 2
[18:30:15] Will use maximum of 2 cores.
[18:30:15] Annotating as >>> Bacteria <<<
[18:30:15] '$file' is not a readable non-empty FASTA file**

_**Ps: Initially, I had all the files in 3 folders, but I have since created a single folder and moved all the contigs into this newly created folder.**_

Thank you in advance for helping.

**Comment by cssulliv** [comment]
Hi,

I am using Prokka 1.14.5. and am getting the same error and found that my files have the following read permission: -rw-r--r-- (not sure if thats the correct type of permission). All file sizes have greater than 0 bytes. All files are in the same folder. Just curious if there are other fixes to this error?

**Comment by tseemann** [comment]
Your file is not called `$file`.  Something is going wrong with your shell script. Are you quoting things like `'$file'` somewhere? Use `"$file"` instead.

**Comment by lj365146534** [comment]
@tseemann 
HI
 I am also grappling with the problem
I use docker to run prokka.
$ docker run staphb/prokka prokka contigs.fa

[09:57:25] This is prokka 1.14.5
[09:57:25] Written by Torsten Seemann <torsten.seemann@gmail.com>
[09:57:25] Homepage is https://github.com/tseemann/prokka
[09:57:25] Local time is Sat Oct 30 09:57:25 2021
[09:57:25] You are not telling me who you are!
[09:57:25] Operating system is linux
[09:57:25] You have BioPerl 1.006924
[09:57:25] System has 80 cores.
[09:57:25] Will use maximum of 8 cores.
[09:57:25] Annotating as >>> Bacteria <<<
[09:57:25] 'contigs.fa' is not a readable non-empty FASTA file

Im very sure it a fasta file and not empty.
I copy prokka/test/plasmid.fna to my pwd
it still not a readable non-empty FASTA file.
Can you help to tell me how to fix this problem?

**Comment by cylcheyanlin** [comment]
> @Biomicrogen That filename should not cause any problems, especially hyphens. I created a file with that name and it worked. For that message to be produced, the file must fail one of these tests: (1) have read permissions (2) be a real file not a folder (3) have a size greater than 0 bytes.
> 
> But glad you solved it.

Hello, I am also getting the same error when I was running PROKKA : xxx is not a readable non-empty FASTA file.
According to your instruction, I have checked my file. The results were as follows:

$ **ls -al** 
![image](https://user-images.githubusercontent.com/95027351/143431259-0bd93056-abf0-44cf-8f0b-b697e7524d6e.png)

 $ **head** **CDC128.fna**
![image](https://user-images.githubusercontent.com/95027351/143431130-57333d54-dbf1-40a3-857f-6449ee69300f.png)

So the file has read permissions, has a size greater than 0 bytes, and is a real file.

But why don't get an error? Could you give me a hand?

**Comment by ShuyiF** [comment]
> > @Biomicrogen That filename should not cause any problems, especially hyphens. I created a file with that name and it worked. For that message to be produced, the file must fail one of these tests: (1) have read permissions (2) be a real file not a folder (3) have a size greater than 0 bytes.
> > But glad you solved it.
> 
> Hello, I am also getting the same error when I was running PROKKA : xxx is not a readable non-empty FASTA file. According to your instruction, I have checked my file. The results were as follows:
> 
> $ **ls -al** ![image](https://user-images.githubusercontent.com/95027351/143431259-0bd93056-abf0-44cf-8f0b-b697e7524d6e.png)
> 
> $ **head** **CDC128.fna** ![image](https://user-images.githubusercontent.com/95027351/143431130-57333d54-dbf1-40a3-857f-6449ee69300f.png)
> 
> So the file has read permissions, has a size greater than 0 bytes, and is a real file.
> 
> But why don't get an error? Could you give me a hand?

I met the same issue! 

My read permissions show as below:
-rw-rw-rw-@

I'm wondering have you solved this problem?

**Comment by Joshua-Macleod** [comment]
> I'm wondering have you solved this problem?

Having the same issue; files appears to be valid FASTA files, >0 bytes, and have following permissions: -rw-rw-r--

Let me know if you find a solution.

**Comment by ShuyiF** [comment]
> 

hi! I met the same issue for my loop. Could you please let me know how you solved it?

**Comment by ShuyiF** [comment]
> > I'm wondering have you solved this problem?
> 
> Having the same issue; files appears to be valid FASTA files, >0 bytes, and have following permissions: -rw-rw-r--
> 
> Let me know if you find a solution.
> 
> Edit: Issue resolved; for loop was feeding incorrect file name to command line as I had misunderstood a script I was referencing.

hi! I met the same issue for my loop. Could you please let me know how you solved it?

**Comment by kyfahh** [comment]
I just change my input file path as short as possible，and it works out!

**Comment by azat-badretdin** [comment]
Glad to hear that, user @kyfahh !

**Comment by alxndrdiaz** [comment]
Hi. Had the same error when trying to run prokka with Docker, FASTA file was not empty. What solved the problem was specifying -v (Bind mount a volume) and -w (Working directory inside the container), see [docker run documentation](https://docs.docker.com/reference/cli/docker/container/run/): 

`docker run -v $(pwd):$(pwd) -w $(pwd) staphb/prokka:latest prokka ...`
